site_name: My Dummy Project
repo_url: https://github.com/M-E-U-E/versioning
site_dir: site

nav:
  - Home: index.md
  - About: about.md
  - Testing: test.md
  - Greetings: hello.md
  - Guide:
      - Introduction: guide/introduction.md
      - Installation: guide/installation.md
      - Usage: guide/usage.md

theme:
  name: material

plugins:
  - search
  - mike
  - macros:
      verbose: false
site_name: My Dummy Project
repo_url: https://github.com/M-E-U-E/versioning
site_dir: site



theme:
  name: material

plugins:
  - search
  - mike
  - macros:
      verbose: false

extra:
  version:
    provider: mike
    default: latest  # Ensure a default version is set
    name: 3.3
    alias: latest
macros:
  current_version: '3.3'
extra:
  version:
    provider: mike
    default: latest
    name: '3.3'
    alias: latest