site_name: My Dummy Project
repo_url: https://github.com/M-E-U-E/versioning
site_dir: site

nav:
  - Home: index.md
  - About: about.md
  - Testing: test.md
  - Greetings: hello.md
  - Guide:
      - Introduction: guide/introduction.md
      - Installation: guide/installation.md
      - Usage: guide/usage.md

theme:
  name: material

plugins:
  - search
  - mike
  - macros

extra:
  version:
    provider: mike
    default: latest  # Ensure a default version is set
    name: 3.1
    alias: latest
